// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Elm = require("bs-elm/src/Elm.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var MainElm = require("../elm/Other/Main.elm");

var elmProgram = MainElm;

var resultRuntime = Elm.mount({
      title: "Text below buttons set in Reason via flags"
    }, undefined, "Other.Main", elmProgram);

if (resultRuntime.tag) {
  console.log(resultRuntime[0]);
} else {
  var runtime = resultRuntime[0];
  Curry._1(runtime.ports.infoForReason.subscribe, (function (info) {
          return Curry._1(runtime.ports.infoForElm.send, "You pressed " + info);
        }));
}

var R;

exports.R = R;
exports.elmProgram = elmProgram;
exports.resultRuntime = resultRuntime;
/* elmProgram Not a pure module */
