// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Elm = require("bs-elm/src/Elm.bs.js");
var MainElm = require("../elm/Other/Main.elm");

var instance = Elm.mount({
      title: "Buttons (title set in Reason via flags)"
    }, undefined, "Other.Main", MainElm);

if (instance.tag) {
  console.log(instance[0]);
} else {
  var i = instance[0];
  var infoForReason = i.ports.infoForReason;
  var infoForElm = i.ports.infoForElm;
  infoForReason.subscribe((function (info) {
          return infoForElm.send("You pressed " + info);
        }));
}

var R = 0;

exports.R = R;
exports.instance = instance;
/* instance Not a pure module */
