// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonElm = require("reason-elm/lib/js/src/ReasonElm.js");
var MainElm   = require("../elm/Main.elm");

var instance = ReasonElm.mount(/* Some */[{
        title: "Buttons (title set in Reason via flags)"
      }], /* None */0, /* None */0, MainElm);

if (instance.tag) {
  console.log(instance[0]);
} else {
  var i = instance[0];
  var infoForReason = i.ports.infoForReason;
  var infoForElm = i.ports.infoForElm;
  infoForReason.subscribe((function (info) {
          return infoForElm.send("You pressed " + info);
        }));
}

var R = 0;

exports.R        = R;
exports.instance = instance;
/* instance Not a pure module */
